'use strict'

export const SERVER_FAILED = 'SERVER_FAILED'
export const API_FAILED = 'API_FAILED'

export const APP_INFO_LOADED = 'APP_INFO_LOADED'
export const PLATFORM_CHANGED = 'PLATFORM_CHANGED'
export const PACK_CHANGED = 'PACK_CHANGED'
export const SEO_PACK_CHANGED = 'SEO_PACK_CHANGED'
export const SEARCH_COLOR_CHANGED = 'SEARCH_COLOR_CHANGED'
export const SEARCH_SHAPE_CHANGED = 'SEARCH_SHAPE_CHANGED'
export const SEARCH_FORMAT_CHANGED = 'SEARCH_FORMAT_CHANGED'

// around app ui
export const ICONS_GRID_STYLE_CHANGED = 'ICONS_GRID_STYLE_CHANGED'
export const EXTENDED_ICONS_GRID_STYLE_CHANGED = 'EXTENDED_ICONS_GRID_STYLE_CHANGED'
export const MODE_CHANGED_TO_ICON = 'MODE_CHANGED_TO_ICON'
export const MODE_CHANGED_TO_COLLECTIONS = 'MODE_CHANGED_TO_COLLECTIONS'

// around sidebars
export const LEFT_SIDEBAR_ENABLED = 'LEFT_SIDEBAR_ENABLED'
export const LEFT_SIDEBAR_DISABLED = 'LEFT_SIDEBAR_DISABLED'
export const LEFT_SIDEBAR_SHOWN = 'LEFT_SIDEBAR_SHOWN'
export const LEFT_SIDEBAR_HIDDEN = 'LEFT_SIDEBAR_HIDDEN'

export const RIGHT_SIDEBAR_ENABLED = 'RIGHT_SIDEBAR_ENABLED'
export const RIGHT_SIDEBAR_DISABLED = 'RIGHT_SIDEBAR_DISABLED'
export const RIGHT_SIDEBAR_SHOWN = 'RIGHT_SIDEBAR_SHOWN'
export const RIGHT_SIDEBAR_HIDDEN = 'RIGHT_SIDEBAR_HIDDEN'
